// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vicon.proto

#ifndef PROTOBUF_vicon_2eproto__INCLUDED
#define PROTOBUF_vicon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_vicon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsrobot_stateImpl();
void InitDefaultsrobot_state();
inline void InitDefaults() {
  InitDefaultsrobot_state();
}
}  // namespace protobuf_vicon_2eproto
class robot_state;
class robot_stateDefaultTypeInternal;
extern robot_stateDefaultTypeInternal _robot_state_default_instance_;

// ===================================================================

class robot_state : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:robot_state) */ {
 public:
  robot_state();
  virtual ~robot_state();

  robot_state(const robot_state& from);

  inline robot_state& operator=(const robot_state& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  robot_state(robot_state&& from) noexcept
    : robot_state() {
    *this = ::std::move(from);
  }

  inline robot_state& operator=(robot_state&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const robot_state& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const robot_state* internal_default_instance() {
    return reinterpret_cast<const robot_state*>(
               &_robot_state_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(robot_state* other);
  friend void swap(robot_state& a, robot_state& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline robot_state* New() const PROTOBUF_FINAL { return New(NULL); }

  robot_state* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const robot_state& from);
  void MergeFrom(const robot_state& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(robot_state* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float tx = 1;
  void clear_tx();
  static const int kTxFieldNumber = 1;
  float tx() const;
  void set_tx(float value);

  // float ty = 2;
  void clear_ty();
  static const int kTyFieldNumber = 2;
  float ty() const;
  void set_ty(float value);

  // float tz = 3;
  void clear_tz();
  static const int kTzFieldNumber = 3;
  float tz() const;
  void set_tz(float value);

  // float ox = 4;
  void clear_ox();
  static const int kOxFieldNumber = 4;
  float ox() const;
  void set_ox(float value);

  // float oy = 5;
  void clear_oy();
  static const int kOyFieldNumber = 5;
  float oy() const;
  void set_oy(float value);

  // float oz = 6;
  void clear_oz();
  static const int kOzFieldNumber = 6;
  float oz() const;
  void set_oz(float value);

  // float ow = 7;
  void clear_ow();
  static const int kOwFieldNumber = 7;
  float ow() const;
  void set_ow(float value);

  // @@protoc_insertion_point(class_scope:robot_state)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float tx_;
  float ty_;
  float tz_;
  float ox_;
  float oy_;
  float oz_;
  float ow_;
  mutable int _cached_size_;
  friend struct ::protobuf_vicon_2eproto::TableStruct;
  friend void ::protobuf_vicon_2eproto::InitDefaultsrobot_stateImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// robot_state

// float tx = 1;
inline void robot_state::clear_tx() {
  tx_ = 0;
}
inline float robot_state::tx() const {
  // @@protoc_insertion_point(field_get:robot_state.tx)
  return tx_;
}
inline void robot_state::set_tx(float value) {
  
  tx_ = value;
  // @@protoc_insertion_point(field_set:robot_state.tx)
}

// float ty = 2;
inline void robot_state::clear_ty() {
  ty_ = 0;
}
inline float robot_state::ty() const {
  // @@protoc_insertion_point(field_get:robot_state.ty)
  return ty_;
}
inline void robot_state::set_ty(float value) {
  
  ty_ = value;
  // @@protoc_insertion_point(field_set:robot_state.ty)
}

// float tz = 3;
inline void robot_state::clear_tz() {
  tz_ = 0;
}
inline float robot_state::tz() const {
  // @@protoc_insertion_point(field_get:robot_state.tz)
  return tz_;
}
inline void robot_state::set_tz(float value) {
  
  tz_ = value;
  // @@protoc_insertion_point(field_set:robot_state.tz)
}

// float ox = 4;
inline void robot_state::clear_ox() {
  ox_ = 0;
}
inline float robot_state::ox() const {
  // @@protoc_insertion_point(field_get:robot_state.ox)
  return ox_;
}
inline void robot_state::set_ox(float value) {
  
  ox_ = value;
  // @@protoc_insertion_point(field_set:robot_state.ox)
}

// float oy = 5;
inline void robot_state::clear_oy() {
  oy_ = 0;
}
inline float robot_state::oy() const {
  // @@protoc_insertion_point(field_get:robot_state.oy)
  return oy_;
}
inline void robot_state::set_oy(float value) {
  
  oy_ = value;
  // @@protoc_insertion_point(field_set:robot_state.oy)
}

// float oz = 6;
inline void robot_state::clear_oz() {
  oz_ = 0;
}
inline float robot_state::oz() const {
  // @@protoc_insertion_point(field_get:robot_state.oz)
  return oz_;
}
inline void robot_state::set_oz(float value) {
  
  oz_ = value;
  // @@protoc_insertion_point(field_set:robot_state.oz)
}

// float ow = 7;
inline void robot_state::clear_ow() {
  ow_ = 0;
}
inline float robot_state::ow() const {
  // @@protoc_insertion_point(field_get:robot_state.ow)
  return ow_;
}
inline void robot_state::set_ow(float value) {
  
  ow_ = value;
  // @@protoc_insertion_point(field_set:robot_state.ow)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vicon_2eproto__INCLUDED
