// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vicon.proto

#include "vicon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace vicon {
class robot_state_requestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<robot_state_request>
      _instance;
} _robot_state_request_default_instance_;
class robot_state_replyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<robot_state_reply>
      _instance;
} _robot_state_reply_default_instance_;
}  // namespace vicon
namespace protobuf_vicon_2eproto {
void InitDefaultsrobot_state_requestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::vicon::_robot_state_request_default_instance_;
    new (ptr) ::vicon::robot_state_request();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::vicon::robot_state_request::InitAsDefaultInstance();
}

void InitDefaultsrobot_state_request() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsrobot_state_requestImpl);
}

void InitDefaultsrobot_state_replyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::vicon::_robot_state_reply_default_instance_;
    new (ptr) ::vicon::robot_state_reply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::vicon::robot_state_reply::InitAsDefaultInstance();
}

void InitDefaultsrobot_state_reply() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsrobot_state_replyImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_request, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, tx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, ty_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, tz_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, ox_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, oy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, oz_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::vicon::robot_state_reply, ow_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::vicon::robot_state_request)},
  { 6, -1, sizeof(::vicon::robot_state_reply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::vicon::_robot_state_request_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::vicon::_robot_state_reply_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "vicon.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013vicon.proto\022\005vicon\"#\n\023robot_state_requ"
      "est\022\014\n\004name\030\001 \001(\t\"g\n\021robot_state_reply\022\n"
      "\n\002tx\030\001 \001(\002\022\n\n\002ty\030\002 \001(\002\022\n\n\002tz\030\003 \001(\002\022\n\n\002ox"
      "\030\004 \001(\002\022\n\n\002oy\030\005 \001(\002\022\n\n\002oz\030\006 \001(\002\022\n\n\002ow\030\007 \001"
      "(\0022M\n\007greeter\022B\n\010SayHello\022\032.vicon.robot_"
      "state_request\032\030.vicon.robot_state_reply\""
      "\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 249);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "vicon.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_vicon_2eproto
namespace vicon {

// ===================================================================

void robot_state_request::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int robot_state_request::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

robot_state_request::robot_state_request()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_vicon_2eproto::InitDefaultsrobot_state_request();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:vicon.robot_state_request)
}
robot_state_request::robot_state_request(const robot_state_request& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:vicon.robot_state_request)
}

void robot_state_request::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

robot_state_request::~robot_state_request() {
  // @@protoc_insertion_point(destructor:vicon.robot_state_request)
  SharedDtor();
}

void robot_state_request::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void robot_state_request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* robot_state_request::descriptor() {
  ::protobuf_vicon_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_vicon_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const robot_state_request& robot_state_request::default_instance() {
  ::protobuf_vicon_2eproto::InitDefaultsrobot_state_request();
  return *internal_default_instance();
}

robot_state_request* robot_state_request::New(::google::protobuf::Arena* arena) const {
  robot_state_request* n = new robot_state_request;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void robot_state_request::Clear() {
// @@protoc_insertion_point(message_clear_start:vicon.robot_state_request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool robot_state_request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:vicon.robot_state_request)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "vicon.robot_state_request.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:vicon.robot_state_request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:vicon.robot_state_request)
  return false;
#undef DO_
}

void robot_state_request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:vicon.robot_state_request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vicon.robot_state_request.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:vicon.robot_state_request)
}

::google::protobuf::uint8* robot_state_request::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:vicon.robot_state_request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "vicon.robot_state_request.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vicon.robot_state_request)
  return target;
}

size_t robot_state_request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vicon.robot_state_request)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void robot_state_request::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vicon.robot_state_request)
  GOOGLE_DCHECK_NE(&from, this);
  const robot_state_request* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const robot_state_request>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vicon.robot_state_request)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vicon.robot_state_request)
    MergeFrom(*source);
  }
}

void robot_state_request::MergeFrom(const robot_state_request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vicon.robot_state_request)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void robot_state_request::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vicon.robot_state_request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void robot_state_request::CopyFrom(const robot_state_request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vicon.robot_state_request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool robot_state_request::IsInitialized() const {
  return true;
}

void robot_state_request::Swap(robot_state_request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void robot_state_request::InternalSwap(robot_state_request* other) {
  using std::swap;
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata robot_state_request::GetMetadata() const {
  protobuf_vicon_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_vicon_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void robot_state_reply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int robot_state_reply::kTxFieldNumber;
const int robot_state_reply::kTyFieldNumber;
const int robot_state_reply::kTzFieldNumber;
const int robot_state_reply::kOxFieldNumber;
const int robot_state_reply::kOyFieldNumber;
const int robot_state_reply::kOzFieldNumber;
const int robot_state_reply::kOwFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

robot_state_reply::robot_state_reply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_vicon_2eproto::InitDefaultsrobot_state_reply();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:vicon.robot_state_reply)
}
robot_state_reply::robot_state_reply(const robot_state_reply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&tx_, &from.tx_,
    static_cast<size_t>(reinterpret_cast<char*>(&ow_) -
    reinterpret_cast<char*>(&tx_)) + sizeof(ow_));
  // @@protoc_insertion_point(copy_constructor:vicon.robot_state_reply)
}

void robot_state_reply::SharedCtor() {
  ::memset(&tx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ow_) -
      reinterpret_cast<char*>(&tx_)) + sizeof(ow_));
  _cached_size_ = 0;
}

robot_state_reply::~robot_state_reply() {
  // @@protoc_insertion_point(destructor:vicon.robot_state_reply)
  SharedDtor();
}

void robot_state_reply::SharedDtor() {
}

void robot_state_reply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* robot_state_reply::descriptor() {
  ::protobuf_vicon_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_vicon_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const robot_state_reply& robot_state_reply::default_instance() {
  ::protobuf_vicon_2eproto::InitDefaultsrobot_state_reply();
  return *internal_default_instance();
}

robot_state_reply* robot_state_reply::New(::google::protobuf::Arena* arena) const {
  robot_state_reply* n = new robot_state_reply;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void robot_state_reply::Clear() {
// @@protoc_insertion_point(message_clear_start:vicon.robot_state_reply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&tx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ow_) -
      reinterpret_cast<char*>(&tx_)) + sizeof(ow_));
  _internal_metadata_.Clear();
}

bool robot_state_reply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:vicon.robot_state_reply)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float tx = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &tx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ty = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ty_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float tz = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &tz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ox = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ox_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float oy = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &oy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float oz = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &oz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ow = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(61u /* 61 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ow_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:vicon.robot_state_reply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:vicon.robot_state_reply)
  return false;
#undef DO_
}

void robot_state_reply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:vicon.robot_state_reply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float tx = 1;
  if (this->tx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->tx(), output);
  }

  // float ty = 2;
  if (this->ty() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->ty(), output);
  }

  // float tz = 3;
  if (this->tz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->tz(), output);
  }

  // float ox = 4;
  if (this->ox() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->ox(), output);
  }

  // float oy = 5;
  if (this->oy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->oy(), output);
  }

  // float oz = 6;
  if (this->oz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->oz(), output);
  }

  // float ow = 7;
  if (this->ow() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->ow(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:vicon.robot_state_reply)
}

::google::protobuf::uint8* robot_state_reply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:vicon.robot_state_reply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float tx = 1;
  if (this->tx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->tx(), target);
  }

  // float ty = 2;
  if (this->ty() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->ty(), target);
  }

  // float tz = 3;
  if (this->tz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->tz(), target);
  }

  // float ox = 4;
  if (this->ox() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->ox(), target);
  }

  // float oy = 5;
  if (this->oy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->oy(), target);
  }

  // float oz = 6;
  if (this->oz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->oz(), target);
  }

  // float ow = 7;
  if (this->ow() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->ow(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vicon.robot_state_reply)
  return target;
}

size_t robot_state_reply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:vicon.robot_state_reply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float tx = 1;
  if (this->tx() != 0) {
    total_size += 1 + 4;
  }

  // float ty = 2;
  if (this->ty() != 0) {
    total_size += 1 + 4;
  }

  // float tz = 3;
  if (this->tz() != 0) {
    total_size += 1 + 4;
  }

  // float ox = 4;
  if (this->ox() != 0) {
    total_size += 1 + 4;
  }

  // float oy = 5;
  if (this->oy() != 0) {
    total_size += 1 + 4;
  }

  // float oz = 6;
  if (this->oz() != 0) {
    total_size += 1 + 4;
  }

  // float ow = 7;
  if (this->ow() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void robot_state_reply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:vicon.robot_state_reply)
  GOOGLE_DCHECK_NE(&from, this);
  const robot_state_reply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const robot_state_reply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:vicon.robot_state_reply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:vicon.robot_state_reply)
    MergeFrom(*source);
  }
}

void robot_state_reply::MergeFrom(const robot_state_reply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:vicon.robot_state_reply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.tx() != 0) {
    set_tx(from.tx());
  }
  if (from.ty() != 0) {
    set_ty(from.ty());
  }
  if (from.tz() != 0) {
    set_tz(from.tz());
  }
  if (from.ox() != 0) {
    set_ox(from.ox());
  }
  if (from.oy() != 0) {
    set_oy(from.oy());
  }
  if (from.oz() != 0) {
    set_oz(from.oz());
  }
  if (from.ow() != 0) {
    set_ow(from.ow());
  }
}

void robot_state_reply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:vicon.robot_state_reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void robot_state_reply::CopyFrom(const robot_state_reply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vicon.robot_state_reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool robot_state_reply::IsInitialized() const {
  return true;
}

void robot_state_reply::Swap(robot_state_reply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void robot_state_reply::InternalSwap(robot_state_reply* other) {
  using std::swap;
  swap(tx_, other->tx_);
  swap(ty_, other->ty_);
  swap(tz_, other->tz_);
  swap(ox_, other->ox_);
  swap(oy_, other->oy_);
  swap(oz_, other->oz_);
  swap(ow_, other->ow_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata robot_state_reply::GetMetadata() const {
  protobuf_vicon_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_vicon_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace vicon

// @@protoc_insertion_point(global_scope)
